Fixed DateTime ValueError when displaying time before 1900.
You would get this error when you visit
http://localhost:8080/minaraad/documenten#c4=sdf, so searching only
for text and not setting any restrictions on the other widgets:

ValueError: year=1000 is before 1900; the datetime strftime() methods require year >= 1900